name = "wg-embedded-cortex-a"
subteam-of = "wg-embedded"
kind = "working-group"

[people]
leads = []
members = [
    "raw-bin",
    "nchong-at-aws",
    "berkus",
]
alumni = [
    "andre-richter",
]

[website]
name = "Embedded Cortex-A team"
description = "Develops and maintains the core of the Cortex-A crate ecosystem"

[[github]]
orgs = ["rust-embedded"]
